name: Build Mania
on:
  push:
    paths:
      - dependencies/**
      - SonicMania/**
      - .github/workflows/build.yml
      - CMakeLists.txt
    branches:
      - master
env:
  GENERAL_FLAGS: "-DWITH_RSDK=ON -DCMAKE_BUILD_TYPE=Release -DMANIA_PRE_PLUS=OFF -DRETRO_DISABLE_PLUS=OFF"
  V5_FLAGS: "-DRETRO_REVISION=2"
  V5U_FLAGS: "-DRETRO_REVISION=3"
  GENERAL_WIN_FLAGS: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
  WIN32_FLAGS: "-DVCPKG_TARGET_TRIPLET=x86-windows-static -A Win32"
  WIN64_FLAGS: "-DVCPKG_TARGET_TRIPLET=x64-windows-static"
jobs:
  mania-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: vcpkg install libtheora libogg --triplet=x86-windows-static
      - name: Build Mania
        run: |
          cmake -B build_v5 ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN32_FLAGS}} ${{env.V5_FLAGS}}
          cmake --build build_v5 --parallel --config Release
          cmake -B build_v5U ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN32_FLAGS}} ${{env.V5U_FLAGS}}
          cmake --build build_v5U --parallel --config Release
      - name: Move artifacts
        run: |
          mkdir artifacts
          mkdir artifacts/v5
          mkdir artifacts/v5U
          mv ./build_v5/Release/*.dll ./artifacts/v5/
          mv
